### PR TITLE
Compress SASS output

### LINKED ISSUE #27: Compress SASS
But preserve the Wordpress-required comment using `/*!` as the comment prefix.

### PR DESCRIPTION
**Pull request by jas14**
Closes #27. The page now links `style.min.css` instead of `style.css`, although we still have a `style.css` output for... convenience? IDK, doesn't hurt to have it.

To build the debug CSS and minified CSS, run `make` in the `neve-child` directory.
To "watch" the minified CSS, run `make watch` in the `neve-child` directory.

### CODE REVIEW

**Comment by mrengy** [comment]
Nice! I haven't come across makefiles before, but that is nifty.

One issue - it seems that when watching with `make watch`, changes to `style.scss` were only applied to the minified css but the unminified one was unchanged, which could lead to confusion.

I tried deleting `style.css` and `style.css.map`, but then I got this error when viewing the themes in WordPress Admin: 

> The active theme is broken. Reverting to the default theme.

since the Wordpress-required comments for the theme in style.css were gone.

I think we could do one of two things to resolve:

1. Delete the unminified css and get the Wordpress-required comments to stay in the minified css (I think you mentioned using exclamation points in the comments inside `style.scss`)
2. Set up `make watch` to compile both `style.css` and `style.min.scss` (didn't seem to be easy with some quick searching I did)

**Comment by jas14** [comment]
What do you think about turning style.css into an empty file with only the WP-required comment and directions to look at the SASS source instead? That unminified CSS only exists for reference anyway.

**Comment by mrengy** [comment]
Yeah, that works! 

I briefly thought about that but then thought it would be disorienting if someone saw the mostly empty style.css file and didn’t know to look in style.scss. But that suggestion to add a comment to that effect sounds great. 
--

**Comment by mrengy** [comment]
Somehow I got a duplicate "wp-content" folder inside the "neve-child" theme at one point when testing this. Not sure how that happened. When I deleted it and then did `make watch` again, it didn't seem to come back though. 🤷  
Image 2020-10-08 at 10 12 18 PM

**Pull request merged**
